<?php

/**
 * @file
 * Contains webform_simple_quiz.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\webform_quiz_elements\Plugin\WebformQuizElementsInterface;

/**
 * Implements hook_help().
 */
function webform_quiz_elements_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_quiz module.
    case 'help.page.webform_quiz_elements':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Build awesome quizzes using the webform module.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function webform_quiz_elements_theme() {
  $info = [
    'webform_quiz_elements_result' => [
      'render element' => 'element',
      'variables' => [
        'quiz_title' => NULL,
        'quiz_options' => [],
      ],
    ],
    'webform_quiz_elements_score' => [
      'render element' => 'element',
      'variables' => [
        'quiz_title' => '',
        'quiz_total_questions_count' => '',
        'quiz_correct_answers_count' => '',
        'quiz_score' => '',
        'quiz_is_pass' => FALSE,
        'quiz_feedback_message' => '',
      ],
    ],
  ];

  return $info;
}

/**
 * Prepares variables for webform quiz result template.
 *
 * Default template: webform-quiz-elements-result.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_webform_quiz_elements_result(array &$variables) {
}

/**
 * Prepares variables for webform quiz score template.
 *
 * Default template: webform-quiz-elements-score.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 */
function template_preprocess_webform_quiz_elements_score(array &$variables) {
}

/**
 * Implements hook_preprocess_HOOK().
 */
function webform_quiz_elements_preprocess_webform_confirmation(array &$variables) {
  if (isset($variables['webform'])) {
    $webform = $variables['webform'];
    $flattened_elements = $webform->getElementsInitializedAndFlattened();

    // Attach style library to preview (preview tokens is not attaching css).
    foreach ($flattened_elements as $element) {
      if (in_array($element['#webform_plugin_id'], WebformQuizElementsInterface::QUIZ_RENDERED_ELEMENTS)) {
        $variables['#attached']['library'][] = 'webform_quiz_elements/styles';
        break;
      }
    }
  }
}

/**
 * Implements hook_token_info_alter().
 */
function webform_quiz_elements_token_info_alter(&$data) {
  module_load_include('inc', 'webform_quiz_elements', 'webform_quiz_elements_.tokens');
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function webform_quiz_elements_theme_suggestions_webform_quiz_elements_score(array $variables) {

}
